name:          "Euclidean Geometry"
description:   "Course Page for UNI Math 3600"
email:         theron.hitchman@uni.edu


url:           "http://theronhitchman.github.io"
baseurl:       "/euclidean-geometry"


markdown:      kramdown
highlighter:   pygments
